### ISSUE TITLE
How to run when installed as dev dependency.

### ISSUE THREAD

**Issue by dmsmidt** [DrewML/chrome-webstore-upload-cli#19]
The current documentation shows how to run the cli tool when it is installed globally.
Could you add documentation about how to run it when installed as dev dependency?

**Comment by greghuc** [comment]
From the root of your project: `./node_modules/.bin/webstore --help`

I'm not sure this needs documenting: this is standard behaviour of a node module: http://stackoverflow.com/questions/9679932/how-to-use-package-installed-locally-in-node-modules

**Comment by DrewML** [comment]
@greghuc hit the nail on the head. You can also call it from an npm run script defined in your `package.json` and just call it with `webstore`, since npm "run" scripts are executed with `node_modules/.bin` in the `PATH`
