### ISSUE TITLE
Use existing zip, or zip up provided dir

### ISSUE THREAD

**Issue by DrewML** [DrewML/chrome-webstore-upload-cli#2]
https://github.com/sindresorhus/refined-twitter/pull/35#discussion_r64515684

**Comment by sindresorhus** [comment]
Does it really need an option? If you point at a directory, zip it, if it's a zip file use it.

**Comment by DrewML** [comment]
Makes sense - we'll go with that.

**Comment by DrewML** [comment]
What do you think makes sense for the option that gets passed as - maybe `--target` (`-t` alias)?

**Comment by sindresorhus** [comment]
`--target` or `--source`

**Comment by DrewML** [comment]
Getting close on this. Just fighting a bug right now where `Yazl` is populating the zip with 0 byte files.

**Comment by DrewML** [comment]
Released in `1.0.0`.
