### ISSUE TITLE
Does auto-publish not trigger an update?

### ISSUE THREAD

**Issue by Failcookie** [DrewML/chrome-webstore-upload-cli#32]
I have a CLI pipeline build that publishes the extension to the Chome Web Store. If I run the command, I can see the updated version number and such in the Chrome Web Store and it appears to be fully updated. I can't even update the package in the Dashboard since they share the same version - perfect! But I don't receive the update on my browser. I'll wait for several days, but see nothing. If I trigger a manual ZIP upload, then the update goes out within hours (as expected).

Here is my command: `webstore upload --source ./dist/chrome.zip --extension-id XX --client-id XX --client-secret XX --refresh-token XX --auto-publish` 

Is there anything that I am missing?

**Comment by bfred-it** [comment]
If the dashboard displays the new version then it’s not an issue with this package, since the upload apparently succeeds

**Comment by Failcookie** [comment]
Okay, perfect! That's all I wanted to verify.
