### ISSUE TITLE
invalid_grant on webstore upload

### ISSUE THREAD

**Issue by dellagustin** [DrewML/chrome-webstore-upload-cli#36]
Hello,

I have been using the cli for sometime successfully to deploy from builds on travis.
My most recent build (it is a long time since I do not do a release) failed with the following error:

```
Response code 400 (Bad Request)
{
    "error": "invalid_grant",
    "error_description": "Bad Request"
}
```

Here is a link to the build: https://travis-ci.org/podStation/podStation/builds/641766403

I have not yet tried to reproduce it locally.
Do you know what this could be?
The error message seems related to oauth authentication flow, but bad request does not look like a recoverable error.

I am using version 1.1.1.

**Comment by fregante** [comment]
Probably the key is incorrect

**Comment by dellagustin** [comment]
Thanks @fregante , 

despite the error indicating otherwise (400 for me seems like you are consuming the API in the wrong way, not that the credentials are invalid), renewing the clientId, clientSecret and refreshToken in Travis solved the problem.

I am assuming it was not a transient problem that would have disappeared in case I tried a new release, because I did not try that.
