### ISSUE TITLE
Feature Request - Add support to .env files

### ISSUE THREAD

**Issue by dellagustin** [DrewML/chrome-webstore-upload-cli#40]
`.env` files can be used to replace setting environment variables.
This is useful for testing and development.

I am planning to implement it myself.
I would use this library https://www.npmjs.com/package/dotenv if I implement, so it would have to be added to the dependencies.

**Comment by fregante** [comment]
Instead of every app having to depend on that and support that file, you could use https://github.com/entropitor/dotenv-cli or any solution from [this question](https://stackoverflow.com/q/19331497/288906). Examples:

```sh
npm i dotenv-cli
dotenv webstore-upload upload --auto-publish
```

or

```sh
eval $(cat .env) webstore-upload upload --auto-publish
```
