### ISSUE TITLE
Error client_secret is missing

### ISSUE THREAD

**Issue by jviney** [DrewML/chrome-webstore-upload-cli#44]
Started to get this error after upgrading to 1.2.1 today:

```
"{\n  \"error\": \"invalid_request\",\n  \"error_description\": \"client_secret is missing.\"\n}"
```

Reverting back to 1.2.0 fixed the issue.

**Comment by fregante** [comment]
Thanks for opening an issue. I posted a simple update (https://github.com/DrewML/chrome-webstore-upload/commit/93a0c3a91d7e363f3421c700e3de4d10c26b54a2) to test the logic in https://github.com/DrewML/chrome-webstore-upload/pull/46, but I thought that the change exclusively avoided _checking_ for the existence of `client_secret` before being sent to the API.

I didn't see that it was actually just a list of parameters, all of which were required:

https://github.com/DrewML/chrome-webstore-upload/commit/93a0c3a91d7e363f3421c700e3de4d10c26b54a2

I'll push 0.4.4 soon

**Comment by fregante** [comment]
Fixed by aa23964 in 0.4.4

**Comment by fregante** [comment]
Since you're using that module through `chrome-webstore-upload-cli`, you'll have to reinstall it and make sure it downloaded `chrome-webstore-upload` v0.4.4 instead of v0.4.3

**Comment by fregante** [comment]
The secret is no longer required **as long as you create a Chrome App**. If you're seeing this message again, please follow the new guide to create new keys: https://github.com/fregante/chrome-webstore-upload/blob/main/How%20to%20generate%20Google%20API%20keys.md

The existing keys should keep working for the foreseeable future though.

**Comment by khuzama98** [comment]
Hey @fregante, I'm having some confusion. I'm trying to implement the github actions for chrome webstore but almost every action I came across asks for the client-secret. Only your cli tool seems to be following the latest updates. So I think I have to implement your cli tool in my workflow. Also let me know one thing that whenever I want to upload the extension the tool will be handling the access token expiration, correct me if I'm wrong.

**Comment by fregante** [comment]
Yes that's the idea. I have not personally used this new key to publish real extensions, but another user reported it was still working months later I think. 

To ensure it works, you have to follow the latest guide because your old keys will still require the secret.

**Comment by khuzama98** [comment]
So if I omit the client-secret it should still work as I'm using the latest guide?
https://github.com/fregante/ghatemplates/blob/main/webext/release.yml
Here in this action there exist secret I'm gonna skip the secret and try it out.

**Comment by fregante** [comment]
That workflow still uses v1, which needs the secret. You can replace v1 with v2 in your workflow.

**Comment by khuzama98** [comment]
Thanks for heads up, but after using the v2 it's showing me this error.

![error-chrome-web-ext](https://user-images.githubusercontent.com/44345364/135839411-48e2c64d-8218-4c8f-8b06-ab2f2a8de7ee.png)

Can you check it and let me know what's causing the issue?

**Comment by AprilSylph** [comment]
What node version is that workflow running? v2 needs 14+ ([noted here](https://github.com/fregante/chrome-webstore-upload-cli/releases/tag/v2.0.0))

**Comment by khuzama98** [comment]
Ohh thanks @AprilSylph , I'll check it with the node 14.

**Comment by fregante** [comment]
Here an extension release I did today with the current version:

- https://github.com/npmhub/npmhub/actions/runs/1301436207
- https://github.com/npmhub/npmhub/blob/main/.github/workflows/release.yml

**Comment by stefanbuck** [comment]
I had a pretty old setup from 2016 and it broke as expected. However following the steps to re-create a new oauth app was super smooth.

**Comment by fregante** [comment]
> it broke as expected

That wasn't expected 🤭 

v2 was released as a breaking release as a precaution but the old code is supposedly still there and working, if the secret is still available.

Anyway glad that the steps were working, 👌 they might be a little different if one is using a pre-existing Google API project

**Comment by stefanbuck** [comment]
> If you created the APIs before version 2.0.0 (September 2021) ...

Therefore I thought it is expected. From my observation and memories the application type `Chrome app` was not available back then and I think I used `Web app` as recommend back then. Maybe this is the reason why.

**Comment by fregante** [comment]
I mean that after the update, your existing config should have kept working, as noted in the release notes:

https://github.com/fregante/chrome-webstore-upload-cli/releases/tag/v2.0.0

Did you try without deleting the client_secret first?

**Comment by stefanbuck** [comment]
> I mean that after the update, your existing config should have kept working

This was not the case. I re-created and update the client_seccret after it was failing.

**Comment by fregante** [comment]
Ouch. Thanks for the report
