### ISSUE TITLE
How do I create those oauth credentials?

### ISSUE THREAD

**Issue by zeke** [DrewML/chrome-webstore-upload-cli#7]
From the usage doc:

```
    --client-id       OAuth2 Client ID
    --client-secret   OAuth2 Client Secret
    --refresh-token   OAuth2 Refresh Token
```

Is this the right URL? https://developer.chrome.com/webstore/using_webstore_api

That's leading me to https://console.developers.google.com/apis/credentials which doesn't feel right. The OAuth flow described there is one where a user consents in-browser. 😱

**Comment by DrewML** [comment]
Yeah, the official Google docs on that topic are pretty dreadful. I burned through an hour or so one night trying to figure it out (but apparently never documented it 😛).

I'll get some updated docs in the readme later today.

**Comment by DrewML** [comment]
Apologies for the delay. Here are the steps:

1. Visit https://console.developers.google.com/apis/api/chromewebstore/overview
2. Click the button to create a new project (confusing, but totally separate from the project for your extension)
3. When redirected back to the `Overview` page, click `Enable` for the API
4. Click the `Credentials` tab on the left-hand side of the page
5. Click `Create credentials >> OAuth Client ID`
![image](https://cloud.githubusercontent.com/assets/5233399/16550256/e543c3fe-416d-11e6-94d7-692a47372843.png)
6. Go through the `Configure consent screen` prompt (you just need to enter a project name)
![image](https://cloud.githubusercontent.com/assets/5233399/16550261/fa8e9d6a-416d-11e6-9a99-636d3c54e271.png)
7. You should then be given a `client_id` and `client_secret`
8. Now, go back to [this page](https://developer.chrome.com/webstore/using_webstore_api), and start at step 9. Make sure you go through the OAuth acceptance page logged in under the account that owns the extension you're planning to publish.
9. Once you've jumped through all the hoops outlined in that document, you should have your `client_id`, `client_secret`, and `refresh_token`.

Pretty ridiculous, right?

Let me know if those steps work for you, and (if you don't mind) please point out any places my steps are lacking along the way. Once you confirm the steps above, I'll update the `readme` with the info.

**Comment by thecotne** [comment]
@DrewML did all that and there is no refresh token there

**Comment by tofutim** [comment]
If you manually go through the Google web page to get the token, does that mean you no longer need the ClientId and ClientSecret? I think this app should make it so you only need the ClientId and Client Secret. Going through the webpage gives you an access token, but that is not the refresh token is it?

**Comment by tofutim** [comment]
@thecotne did you figure it out? It is terribly manually, but step 9 will give you an "authorization code", which you then use in curl to retrieve something like this:

{
  "access_token" : "aaa",
  "token_type" : "Bearer",
  "expires_in" : 3600,
  "refresh_token" : "zzzz"
}

after you get the refresh_token you can use this at any time to make a new access_token to do the deeds

**Comment by thecotne** [comment]
> did you figure it out?

could not


but i found another script https://github.com/pastak/chrome-webstore-manager

does all same things ...

**Comment by tofutim** [comment]
that script looks more thorough (handling the authentication and access code) - cool thanks for the lead.

**Comment by tofutim** [comment]
step 1. use your clientId and webbrowser to obtain an authorization code

https://accounts.google.com/o/oauth2/auth?response_type=code&scope=https://www.googleapis.com/auth/chromewebstore&client_id=$CLIENT_ID&redirect_uri=urn:ietf:wg:oauth:2.0:oob

step 2. use curl, your client id, your client secret and the authorization to get the access token and refresh token

> curl "https://accounts.google.com/o/oauth2/token" -d \
"client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&code=$CODE&grant_type=authorization_code&redirect_uri=urn:ietf:wg:oauth:2.0:oob"

not sure why you couldn't programmatically obtain these, maybe it is too hard to programmatically push the button?

**Comment by thecotne** [comment]
sorry i missed step 8 from DrewML guide 

because it says "go **_back_** to this page" i have not clicked it and ...

i was thinking back to google developer console

**Comment by micky2be** [comment]
There are some step missing where I'm not quite sure what to do.

> 3. When redirected back to the Overview page, click Enable for the API
Ok but but should we create the API key or not from there?

> Step 5 to 7
What Application type should we select? (If I select Chrome App it doesn't give me any client_secret)

**Comment by thecotne** [comment]
@micky2be guide is actually OK

> Ok but but should we create the API key or not from there?

on step 5 you create Click "OAuth Client ID" kinda like API key

> What Application type should we select? (If I select Chrome App it doesn't give me any client_secret)

it's not chrome app it's for terminal use

and don't miss step 8

**Comment by micky2be** [comment]
Hmmm, I believe I did everything correctly.
Using a REST client it seems to work with https://www.googleapis.com/oauth2/v3/token instead of https://accounts.google.com/o/oauth2/token

**Comment by bfred-it** [comment]
The confusion here is that CWU asks for a `refreshToken` but we actually need the `accessToken`

I wrote an extended guide in the main repo: 🎉 https://github.com/DrewML/chrome-webstore-upload/pull/5

<details><summary>I'm hosting the guide's images in this comment.</summary>

<img width="296" alt="chrome-apis-create-project" src="https://cloud.githubusercontent.com/assets/1402241/21517725/55e5c626-cc96-11e6-9b55-ec9c80e10ec4.png">

<img width="671" alt="chrome-apis-enable-webstore" src="https://cloud.githubusercontent.com/assets/1402241/21517842/2a9f36a4-cc97-11e6-8ffa-ad49ac2ca3ce.png">

<img width="828" alt="create-credentials" src="https://cloud.githubusercontent.com/assets/1402241/21517881/64f727f8-cc97-11e6-9c6b-b347b71352bf.png">

<img width="615" alt="configure consent screen" src="https://cloud.githubusercontent.com/assets/1402241/21517907/92640e0e-cc97-11e6-93f7-d077664eead9.png">

<img width="187" alt="client type id" src="https://cloud.githubusercontent.com/assets/1402241/21517952/d1f36fce-cc97-11e6-92c0-de4485d97736.png">

<img width="420" alt="refresh token" src="https://cloud.githubusercontent.com/assets/1402241/21518094/c3033bb0-cc98-11e6-82bb-f6c69ca103fe.png">

<img width="750" alt="access token" src="https://cloud.githubusercontent.com/assets/1402241/21518331/9b7e3b42-cc9a-11e6-8d65-cde5ba5ea105.png">
<details>
